# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Заметки
email: romanov.leonid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  О HTML, CSS и иже с ними
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leonid.github.io" # the base hostname & protocol for your site

tags:
  aaa
  test

author:
  name : Leonid Romanov
  email : romanov.leonid@gmail.com
  github : https://github.com/leonid
twitter_username: _leonid
github_username:  leonid

# Build settings
markdown: kramdown
